name: 'License Compliance Checker'
description: 'Check the licenses of dependencies and output to step summary if restricted licenses are found'
inputs:
  allow_list:
    description: 'Regex pattern for allowed licenses'
    required: true
  block_list:
    description: 'Regex pattern for blocked licenses'
    required: true
  runtime:
    description: 'Project runtime'
    required: true
  show_all:
    description: 'Whether to show all license information'
    required: false
    default: 'false'
  python_version:
    description: 'Python version'
    required: false
    default: '3.10'
  node_version:
    description: 'Node.js version'
    required: false
    default: '18'
  source_path:
    descriptions: 'subpath for source that includes requirments.txt or package.json'
    required: false
    default: '.'
  export_requirements:
    description: 'when using Poetry, export the requirements.txt file from pyproject.toml basis'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Check out Code'
      uses: actions/checkout@v4

    - name: 'Setup Environment'
      if: ${{ inputs.runtime == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: 'Setup Environment'
      if: ${{ inputs.runtime == 'python' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: 'Change to source path'
      run: |
        cd ${{ github.workspace }}/${{ inputs.source_path }}
        pwd
        ls -la
      shell: bash

    - name: 'Export requirements from pyproject.toml'
      run: |
        if [[ "${{ inputs.export_requirements }}" == "true" ]]; then
          cd ${{ github.workspace }}/${{ inputs.source_path }} && make install-poetry
          poetry export -f requirements.txt --output ./requirements.txt --without-hashes
          ls -la
        fi
      shell: bash

    - name: 'Install Dependencies'
      run: |
        if [[ "${{ inputs.runtime }}" == "node" ]]; then
          npm ci
          npm i license-checker
        elif [[ "${{ inputs.runtime }}" == "python" ]]; then
          pip install -r requirements.txt
          pip install pip-licenses
        fi
      shell: bash
      if: ${{ inputs.runtime == 'node' || inputs.runtime == 'python' }}

    - name: 'Run license checker'
      run: |
        if [[ "${{ inputs.runtime }}" == "node" ]]; then
          npx license-checker --csv --direct >> licenses.csv
        elif [[ "${{ inputs.runtime }}" == "python" ]]; then
          pip-licenses --format=csv --with-urls --no-version --output-file=licenses.csv
        fi
      shell: bash
      if: ${{ inputs.runtime == 'node' || inputs.runtime == 'python' }}

    - name: 'Check Dependencies Licenses'
      run: |
        chmod +x ${{ github.action_path }}/scripts/license_check.sh
        ${{ github.action_path }}/scripts/license_check.sh licenses.csv "${{ inputs.allow_list }}" "${{ inputs.block_list }}"
      shell: bash

    - name: 'Show All License Information'
      run: |
        if [[ "${{ inputs.show_all }}" == 'true' ]]; then
          chmod +x ${{ github.action_path }}/scripts/show_all_licenses.sh
          ${{ github.action_path }}/scripts/show_all_licenses.sh licenses.csv "${{ inputs.allow_list }}" "${{ inputs.block_list }}"
        fi
      shell: bash
      if: always()
